# Generated by Django 2.0.13 on 2019-04-20 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('date_expires', models.DateTimeField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('locked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'locking_lock',
                'permissions': (('can_unlock', "Can remove other user's locks"),),
            },
        ),
        migrations.AlterUniqueTogether(
            name='lock',
            unique_together={('content_type', 'object_id')},
        ),
    ]
